name: Extrair readmes.zip

on:
  push:
    paths:
      - "readmes.zip"

jobs:
  unzip-readmes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Extrair readmes.zip
        run: |
          unzip -o readmes.zip -d readmes

      - name: Commit e Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add readmes
          git commit -m "Extra√≠do readms.zip"
          git push || echo "Nada para enviar"
